export const SET_REQUESTS = 'SET_REQUESTS';
export const SET_REQUEST = 'SET_REQUEST';
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const DELETE_REQUESTS = 'DELETE_REQUESTS';
export const SET_REQUESTS_FILTERS = 'SET_REQUESTS_FILTERS';
