# Generated by Django 3.2.7 on 2021-10-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211002_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_body',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Request body'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_headers',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Request headers'),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_body',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Response body'),
        ),
    ]
