# Generated by Django 3.2.7 on 2021-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211002_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_body',
            field=models.TextField(blank=True, null=True, verbose_name='Request body'),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_body',
            field=models.TextField(blank=True, null=True, verbose_name='Response body'),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Response headers'),
        ),
    ]
