# Generated by Django 3.2.7 on 2021-10-04 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_request_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Request id'),
        ),
    ]
