# Generated by Django 3.2.7 on 2021-10-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20211023_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='project',
        ),
        migrations.AlterField(
            model_name='service',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, to='tracks.Track', verbose_name='Tracks'),
        ),
    ]
