# Generated by Django 3.2.7 on 2021-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20211023_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceactivity',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='Index'),
        ),
    ]
