# Generated by Django 3.2.7 on 2021-10-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_serviceactivity_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceactivity',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracks.serviceactivity', verbose_name='Activity'),
        ),
    ]
