# Generated by Django 3.2.7 on 2021-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20211025_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='activity',
        ),
        migrations.AddField(
            model_name='serviceactivity',
            name='services',
            field=models.ManyToManyField(blank=True, to='tracks.Service', verbose_name='Services'),
        ),
    ]
