# Generated by Django 3.2.7 on 2021-10-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_trackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='requests',
            field=models.ManyToManyField(to='tracks.TrackRequest', verbose_name='Requests'),
        ),
    ]
