# Generated by Django 3.2.7 on 2021-10-30 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20211030_2052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0009_auto_20211027_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackrequest',
            name='additionalInfo',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='errorMessage',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='success',
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='duration',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='isCustom',
            field=models.BooleanField(default=False, verbose_name='Is request custom'),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='method',
            field=models.CharField(default='GET', max_length=20, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='requestBody',
            field=models.TextField(blank=True, null=True, verbose_name='Request body'),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='requestHeaders',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Request headers'),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='requestUrl',
            field=models.CharField(default='dsfds', max_length=500, verbose_name='Request url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='responseBody',
            field=models.TextField(blank=True, null=True, verbose_name='Response body'),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='responseHeaders',
            field=models.JSONField(blank=True, default=dict, verbose_name='Response headers'),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='statusCode',
            field=models.IntegerField(default=200, verbose_name='Response status code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='tracks.Track', verbose_name='Tracks'),
        ),
        migrations.AlterField(
            model_name='track',
            name='requests',
            field=models.ManyToManyField(blank=True, to='tracks.TrackRequest', verbose_name='Requests'),
        ),
        migrations.AlterField(
            model_name='trackrequest',
            name='requestId',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Request id'),
        ),
    ]
