# Generated by Django 3.2.7 on 2021-10-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_auto_20211030_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='requests',
        ),
        migrations.DeleteModel(
            name='TrackRequest',
        ),
    ]
