# Generated by Django 3.2.7 on 2021-10-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0012_auto_20211030_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackrequest',
            name='isCustom',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='user',
        ),
    ]
