# Generated by Django 3.2.7 on 2021-10-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0013_auto_20211030_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackrequest',
            name='service',
        ),
    ]
