# Generated by Django 3.2.7 on 2021-10-13 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0015_auto_20211009_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.BigIntegerField(verbose_name='Created')),
                ('deleted', models.BigIntegerField(verbose_name='Deleted')),
                ('filtered', models.BigIntegerField(verbose_name='Filtered')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
                ('requests', models.ManyToManyField(to='projects.Request', verbose_name='Requests')),
            ],
        ),
    ]
