# Generated by Django 3.2.7 on 2021-10-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeststat',
            old_name='response_code',
            new_name='statusCode',
        ),
    ]
