# Generated by Django 3.2.7 on 2021-10-13 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20211009_1756'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveIntegerField(verbose_name='Status code')),
                ('method', models.CharField(max_length=20, verbose_name='Method')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('action', models.CharField(choices=[('create', 'create'), ('delete', 'delete'), ('filter', 'filter')], default='create', max_length=10, verbose_name='Action')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
        ),
        migrations.DeleteModel(
            name='RequestStats',
        ),
    ]
