# Generated by Django 3.2.7 on 2021-10-13 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20211013_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttrack',
            old_name='status_code',
            new_name='response_code',
        ),
        migrations.AlterField(
            model_name='requesttrack',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
