# Generated by Django 3.2.7 on 2021-11-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_response_code_requeststat_statuscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststat',
            name='duration',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Duration in seconds'),
        ),
    ]
