# Generated by Django 3.2.7 on 2021-10-13 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20211013_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttrack',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
