# Generated by Django 3.2.7 on 2021-10-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20211009_1756'),
        ('stats', '0004_alter_requesttrack_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestTrack',
            new_name='RequestStat',
        ),
    ]
