export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_PROJECT = 'SET_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SET_SELECTED_MEMBERS = 'SET_SELECTED_MEMBERS';

export const SET_INVITE_MEMBER_MODAL = 'SET_INVITE_MEMBER_MODAL';
