# Generated by Django 3.2.7 on 2021-10-16 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
    ]
