# Generated by Django 3.2.7 on 2021-10-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_last_updated_project_lastupdated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsettings',
            old_name='exclude_methods',
            new_name='excludeMethods',
        ),
        migrations.RenameField(
            model_name='projectsettings',
            old_name='exclude_statuses',
            new_name='excludeStatuses',
        ),
        migrations.RenameField(
            model_name='projectsettings',
            old_name='filter_methods',
            new_name='filterMethods',
        ),
    ]
