# Generated by Django 3.2.7 on 2021-10-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectsettings_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requests',
        ),
    ]
