# Generated by Django 3.2.7 on 2021-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211002_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='method',
            field=models.CharField(default='GET', max_length=20, verbose_name='Method'),
        ),
    ]
