# Generated by Django 3.2.7 on 2021-10-04 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_request_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Request id'),
        ),
    ]
