# Generated by Django 3.2.7 on 2021-10-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short',
            field=models.CharField(default='LL', max_length=2, verbose_name='Short name'),
            preserve_default=False,
        ),
    ]
