# Generated by Django 3.2.7 on 2021-10-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectsettings_filterstatuscodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='realtimeUpdates',
            field=models.JSONField(blank=True, default={'normalized': 10, 'unit': 'seconds', 'value': 10}, verbose_name='Realtime update'),
        ),
    ]
