# Generated by Django 3.2.7 on 2021-10-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectsettings_realtimeupdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='realtimeUpdates',
        ),
    ]
