# Generated by Django 3.2.7 on 2021-10-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20211009_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to='projects.Member', verbose_name='Members'),
        ),
    ]
