# Generated by Django 3.2.7 on 2021-10-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_projectsettings_realtimeupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram channel'),
        ),
        migrations.AddField(
            model_name='project',
            name='telegram_channel_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram channel id'),
        ),
    ]
