# Generated by Django 3.2.7 on 2021-10-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20211025_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slack channel'),
        ),
    ]
