# Generated by Django 3.2.7 on 2021-10-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20211009_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_methods', models.JSONField(blank=True, default=list, verbose_name='Exclude methods')),
                ('exclude_statuses', models.JSONField(blank=True, default=list, verbose_name='Exclude statuses')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
        ),
    ]
