# Generated by Django 3.2.7 on 2021-10-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('projects', '0017_projecttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask', verbose_name='Task'),
        ),
    ]
