# Generated by Django 3.2.7 on 2021-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20211030_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='trackPatterns',
            field=models.JSONField(blank=True, default={'{int}': '[0-9]+', '{str}': '([^>]*)', '{uuid}': '\\b[0-9a-f]{8}\\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\\b[0-9a-f]{12}\\b'}, verbose_name='Track patterns'),
        ),
    ]
