# Generated by Django 3.2.7 on 2021-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projectsettings_trackpatterns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='trackPatterns',
            field=models.JSONField(blank=True, default=[{'pattern': '{int}', 'regex': '[0-9]+'}, {'pattern': '{uuid}', 'regex': '\\b[0-9a-f]{8}\\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\\b[0-9a-f]{12}\\b'}, {'pattern': '{str}', 'regex': '([^>]*)'}], verbose_name='Track patterns'),
        ),
    ]
