# Generated by Django 3.2.7 on 2021-11-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaction',
            name='title',
        ),
        migrations.AddField(
            model_name='projectaction',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title[en]'),
        ),
        migrations.AddField(
            model_name='projectaction',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title[ru]'),
        ),
    ]
