# Generated by Django 3.2.7 on 2021-10-16 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Request id')),
                ('method', models.CharField(default='GET', max_length=20, verbose_name='Method')),
                ('request_url', models.CharField(max_length=500, verbose_name='Request url')),
                ('request_headers', models.JSONField(blank=True, default=list, null=True, verbose_name='Request headers')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='Request body')),
                ('response_code', models.IntegerField(verbose_name='Response status code')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Response body')),
                ('response_headers', models.JSONField(blank=True, default=dict, verbose_name='Response headers')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
