# Generated by Django 3.2.7 on 2021-10-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='remoteAddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote server address'),
        ),
    ]
