# Generated by Django 3.2.7 on 2021-10-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_request_remoteaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='remoteAddress',
        ),
    ]
