# Generated by Django 3.2.7 on 2021-10-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_remove_request_remoteaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_body',
            new_name='requestBody',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request_headers',
            new_name='requestHeaders',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request_id',
            new_name='requestId',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request_url',
            new_name='requestUrl',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='response_body',
            new_name='responseBody',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='response_headers',
            new_name='responseHeaders',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='response_code',
            new_name='statusCode',
        ),
    ]
