# Generated by Django 3.2.7 on 2021-10-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_auto_20211017_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestTracks',
            new_name='Track',
        ),
    ]
