# Generated by Django 3.2.7 on 2021-10-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_requests'),
        ('calls', '0009_auto_20211017_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='track',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
    ]
