# Generated by Django 3.2.7 on 2021-10-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_auto_20211017_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='responseBodyContains',
            field=models.TextField(blank=True, null=True, verbose_name='Response body contains'),
        ),
    ]
