# Generated by Django 3.2.7 on 2021-10-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_alter_track_responsebodycontains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='statusCode',
        ),
        migrations.AddField(
            model_name='track',
            name='statusCodes',
            field=models.JSONField(default=list, verbose_name='Status codes'),
        ),
    ]
