# Generated by Django 3.2.7 on 2021-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_auto_20211017_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='timesActual',
            field=models.PositiveIntegerField(default=0, verbose_name='How many times error actually happens'),
        ),
        migrations.AlterField(
            model_name='track',
            name='times',
            field=models.PositiveIntegerField(default=1, verbose_name='How many times error should happened'),
        ),
    ]
