# Generated by Django 3.2.7 on 2021-10-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0013_auto_20211017_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='duration',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Duration in seconds'),
        ),
    ]
