# Generated by Django 3.2.7 on 2021-10-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_request_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
