# Generated by Django 3.2.7 on 2021-11-01 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_projectsettings_trackpatterns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0015_delete_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('body', models.JSONField(default=dict, verbose_name='Body')),
                ('domain', models.CharField(blank=True, max_length=500, null=True, verbose_name='Domain')),
                ('headers', models.JSONField(blank=True, default=list, verbose_name='Headers')),
                ('methods', models.JSONField(blank=True, default=list, verbose_name='Methods')),
                ('statusCodes', models.JSONField(blank=True, default=dict, verbose_name='Status codes')),
                ('time', models.JSONField(blank=True, default=dict, verbose_name='Time')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
