# Generated by Django 3.2.7 on 2021-11-01 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_projectsettings_trackpatterns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0016_requestsfilters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestsFilters',
            new_name='RequestsFilter',
        ),
    ]
