# Generated by Django 3.2.7 on 2021-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0017_rename_requestsfilters_requestsfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsfilter',
            name='title',
            field=models.CharField(default='sadsadasdas', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
