# Generated by Django 3.2.7 on 2021-11-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0020_auto_20211105_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='queryParams',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Query params'),
        ),
    ]
