# Generated by Django 3.2.7 on 2021-11-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectsettings_trackdomains'),
        ('calls', '0021_request_queryparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequestshistory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='customrequestshistory',
            name='queryParams',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Query params'),
        ),
    ]
