# Generated by Django 3.2.7 on 2021-11-08 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0022_auto_20211107_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequestshistory',
            name='requestId',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Request id'),
        ),
    ]
