# Generated by Django 3.2.7 on 2021-11-08 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0023_customrequestshistory_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequestshistory',
            name='requestId',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Request id'),
        ),
    ]
