export const SET_STATS_FILTERS = 'SET_STATS_FILTERS';
export const SET_STATS_GROUP_BY = 'SET_STATS_GROUP_BY';

export const SET_REQUESTS_STATS = 'SET_REQUESTS_STATS';

export const SET_RATIO_STATUS_CODES = 'SET_RATIO_STATUS_CODES';
export const SET_NUMBER_OF_REQUESTS = 'SET_NUMBER_OF_REQUESTS';
