# Generated by Django 3.2.7 on 2021-10-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(blank=True, choices=[('developer', 'developer'), ('quality assurance', 'quality assurance'), ('team lead', 'team lead'), ('product manager', 'product manager')], max_length=100, null=True, verbose_name='Job title'),
        ),
    ]
