# Generated by Django 3.2.7 on 2021-10-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
