# Generated by Django 3.2.7 on 2021-10-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_apitoken_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.UUIDField(editable=False, unique=True, verbose_name='Token'),
        ),
    ]
