# Generated by Django 3.2.7 on 2021-10-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_apitoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.UUIDField(unique=True, verbose_name='Token'),
        ),
    ]
