# Generated by Django 3.2.7 on 2021-10-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_apitoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='User telegram id'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User telegram username'),
        ),
    ]
