# Generated by Django 3.2.7 on 2021-11-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='skeletonAnimation',
            field=models.CharField(blank=True, choices=[('pulse', 'pulse'), ('wave', 'wave'), (None, None)], default='wave', max_length=20, null=True, verbose_name='Skeleton animation'),
        ),
    ]
