# Generated by Django 3.2.7 on 2021-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usersettings_skeletonanimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='customRequestsHeaders',
            field=models.JSONField(default=list, verbose_name='Custom requests headers'),
        ),
    ]
