# Generated by Django 3.2.7 on 2021-11-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usersettings_customrequestsheaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='customRequestsHeaders',
            field=models.JSONField(default=dict, verbose_name='Custom requests headers'),
        ),
    ]
