export const SET_CUSTOM_REQUESTS = 'SET_CUSTOM_REQUESTS';
export const SET_CUSTOM_REQUEST = 'SET_CUSTOM_REQUEST';
export const CREATE_CUSTOM_REQUEST = 'CREATE_CUSTOM_REQUEST';
export const UPDATE_CUSTOM_REQUEST = 'UPDATE_CUSTOM_REQUEST';
export const DELETE_CUSTOM_REQUEST = 'DELETE_CUSTOM_REQUEST';

export const SET_CUSTOM_REQUESTS_HISTORY = 'SET_CUSTOM_REQUESTS_HISTORY';
export const CREATE_CUSTOM_REQUESTS_HISTORY = 'CREATE_CUSTOM_REQUESTS_HISTORY';
export const SET_CUSTOM_REQUEST_HISTORY_PAGINATION = 'SET_CUSTOM_REQUEST_HISTORY_PAGINATION';
