# Generated by Django 3.2.7 on 2021-11-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remoteAddress',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Remote address'),
        ),
    ]
