export const SET_ROLE = 'SET_ROLE';

export const SET_SELECTED_MEMBERS = 'SET_SELECTED_MEMBERS';
export const SET_SELECTED_ROLES = 'SET_SELECTED_ROLES';

export const SET_INVITE_MEMBER_MODAL = 'SET_INVITE_MEMBER_MODAL';
export const SET_CREATE_ROLE_MODAL = 'SET_CREATE_ROLE_MODAL';
