export const SET_ACTIVITIES = 'SET_ACTIVITIES';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const MOVE_SERVICE = 'MOVE_SERVICE';
export const SET_SERVICE = 'SET_SERVICE';
export const SET_CREATE_TRACK_MODAL = 'SET_CREATE_TRACK_MODAL';
