export const SET_REQUESTS = 'SET_REQUESTS';
export const SET_REQUEST = 'SET_REQUEST';
export const DELETE_REQUESTS = 'DELETE_REQUESTS';

export const SET_REQUESTS_FILTERS = 'SET_REQUESTS_FILTERS';
export const SET_SELECTED_REQUESTS = 'SET_SELECTED_REQUESTS';
export const SET_REQUESTS_REALTIME = 'SET_REQUESTS_REALTIME';
export const SET_REQUESTS_PAGINATION = 'SET_REQUESTS_PAGINATION';
export const SET_REQUESTS_FILTERS_SIDEBAR = 'SET_REQUESTS_FILTERS_SIDEBAR';
export const SET_REQUESTS_TIME_FILTER_MODAL = 'SET_REQUESTS_TIME_FILTER_MODAL';
export const SET_REQUESTS_STATS_FILTERS = 'SET_REQUESTS_STATS_FILTERS';
export const SET_REQUESTS_STATS_GROUP_BY = 'SET_REQUESTS_STATS_GROUP_BY';

export const SET_SAVED_REQUESTS_FILTERS = 'SET_SAVED_REQUESTS_FILTERS';
export const CREATE_SAVED_REQUESTS_FILTER = 'CREATE_SAVED_REQUESTS_FILTER';
export const DELETE_SAVED_REQUESTS_FILTER = 'DELETE_SAVED_REQUESTS_FILTER';
